name: "Release to Marketplace"

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: latest

    - name: Install vsce
      run: npm install -g @vscode/vsce --save-dev

    - name: Package
      run: vsce package

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        path: '*.vsix'
        retention-days: 90

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: '*.vsix'
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true

    - name: Publish
      if: success() && startsWith(github.ref, 'refs/tags/')
      run: npm run deploy
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
